version: '3.8'

services:
  api:
    volumes:
      - ./app:/app/app
    environment:
      - DEBUG=true
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  downloader:
    volumes:
      - ./docker/downloader/app.py:/app/app.py
    command: uvicorn app:app --host 0.0.0.0 --port 8001 --reload

  transcriber:
    volumes:
      - ./docker/transcriber/app.py:/app/app.py
    command: uvicorn app:app --host 0.0.0.0 --port 8002 --reload
